- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-zaqarclient-dsvm-functional
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-zaqarclient-dsvm-functional
